apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - image: <docker-username>/server-querier
        name: container1
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs